// server/web/ui/src/components/WorkersPage.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { People, Schedule, Dns } from '@mui/icons-material';
import '../styles/WorkersPage.css';

interface Worker {
  name: string;
  id: string;
  queue_name: string;
  last_seen: string;
}

interface WorkersPageProps {
  token: string;
  setShowJobTable: React.Dispatch<React.SetStateAction<boolean>>;
  setErrorText: React.Dispatch<React.SetStateAction<string>>;
}

const WorkersPage: React.FC<WorkersPageProps> = ({ token, setShowJobTable, setErrorText }) => {
  const [workers, setWorkers] = useState<Worker[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const fetchWorkers = async () => {
      try {
        setLoading(true);
        const response = await axios.get('/api/v1/workers', {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        setWorkers(response.data);
      } catch (error) {
        console.error('Error fetching workers:', error);
        setShowJobTable(false);
        if (error instanceof Error) {
          setErrorText(error.message);
        }
      } finally {
        setLoading(false);
      }
    };

    fetchWorkers();
  }, [token, setShowJobTable, setErrorText]);

  const getInitials = (name: string) => {
    return name
      .split('-')
      .map((part) => part[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  };

  const formatLastSeen = (lastSeen: string) => {
    const date = new Date(lastSeen);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    return `${diffDays}d ago`;
  };

  if (loading) {
    return (
      <div className="workers-page">
        <div className="workers-header">
          <h1 className="workers-title">Workers</h1>
        </div>
        <div className="workers-loading">
          <div className="workers-spinner" />
        </div>
      </div>
    );
  }

  return (
    <div className="workers-page">
      <div className="workers-header">
        <h1 className="workers-title">Workers ({workers.length})</h1>
      </div>

      {workers.length > 0 ? (
        <div className="workers-grid">
          {workers.map((worker) => (
            <div key={worker.id} className="worker-card">
              <div className="worker-card-header">
                <div className="worker-avatar">{getInitials(worker.name)}</div>
                <div className="worker-info">
                  <div className="worker-name">{worker.name}</div>
                  <div className="worker-id">{worker.id.slice(0, 8)}...</div>
                </div>
                <div className="worker-status">
                  <span className="worker-status-dot" />
                  Online
                </div>
              </div>
              <div className="worker-card-body">
                <div className="worker-detail">
                  <span className="worker-detail-label">
                    <Dns fontSize="small" />
                    Queue
                  </span>
                  <span className="worker-detail-value">{worker.queue_name}</span>
                </div>
                <div className="worker-detail">
                  <span className="worker-detail-label">
                    <Schedule fontSize="small" />
                    Last Seen
                  </span>
                  <span className="worker-detail-value">{formatLastSeen(worker.last_seen)}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="workers-empty">
          <People className="workers-empty-icon" />
          <p className="workers-empty-text">No workers available</p>
        </div>
      )}
    </div>
  );
};

export default WorkersPage;

// server/web/ui/src/lib/components/WorkersPage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { authStore } from '$lib/stores';
  import { fetchWorkers, type Worker } from '$lib/api';
  import IconPeople from '$lib/components/icons/IconPeople.svelte';
  import IconDns from '$lib/components/icons/IconDns.svelte';
  import IconSchedule from '$lib/components/icons/IconSchedule.svelte';
  import Spinner from '$lib/components/Spinner.svelte';

  let workers = $state<Worker[]>([]);
  let loading = $state(true);

  onMount(async () => {
    const token = authStore.getToken();
    if (!token) {
      goto('/');
      return;
    }

    try {
      workers = await fetchWorkers(token);
    } catch (error) {
      authStore.logout();
      goto('/');
    } finally {
      loading = false;
    }
  });

  function getInitials(name: string) {
    return name
      .split('-')
      .map((part) => part[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);
  }

  function formatLastSeen(lastSeen: string) {
    const date = new Date(lastSeen);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    return `${diffDays}d ago`;
  }
</script>

<div class="workers-page">
  <div class="workers-header">
    <h1 class="workers-title">Workers ({workers.length})</h1>
  </div>

  {#if loading}
    <div class="workers-loading">
      <Spinner size="2rem" />
    </div>
  {:else if workers.length > 0}
    <div class="workers-grid">
      {#each workers as worker}
        <div class="worker-card">
          <div class="worker-card-header">
            <div class="worker-avatar">{getInitials(worker.name)}</div>
            <div class="worker-info">
              <div class="worker-name">{worker.name}</div>
              <div class="worker-id">{worker.id.slice(0, 8)}...</div>
            </div>
            <div class="worker-status">
              <span class="worker-status-dot"></span>
              Online
            </div>
          </div>
          <div class="worker-card-body">
            <div class="worker-detail">
              <span class="worker-detail-label">
                <IconDns class="w-4 h-4" />
                Queue
              </span>
              <span class="worker-detail-value">{worker.queue_name}</span>
            </div>
            <div class="worker-detail">
              <span class="worker-detail-label">
                <IconSchedule class="w-4 h-4" />
                Last Seen
              </span>
              <span class="worker-detail-value">{formatLastSeen(worker.last_seen)}</span>
            </div>
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <div class="workers-empty">
      <IconPeople class="workers-empty-icon" />
      <p class="workers-empty-text">No workers available</p>
    </div>
  {/if}
</div>

<style>
  .workers-page {
    padding: var(--spacing-lg);
    max-width: 1400px;
    margin: 0 auto;
  }

  .workers-header {
    margin-bottom: var(--spacing-xl);
  }

  .workers-title {
    font-size: var(--font-size-3xl);
    font-weight: var(--font-weight-bold);
    color: var(--text-primary);
  }

  .workers-loading {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 200px;
  }

  .workers-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: var(--spacing-lg);
  }

  .worker-card {
    background-color: var(--bg-card);
    border: 1px solid var(--border-color);
    border-radius: var(--border-radius-lg);
    overflow: hidden;
    box-shadow: var(--shadow-sm);
  }

  .worker-card-header {
    display: flex;
    align-items: center;
    gap: var(--spacing-md);
    padding: var(--spacing-lg);
    border-bottom: 1px solid var(--border-color);
  }

  .worker-avatar {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 3rem;
    height: 3rem;
    background-color: var(--color-primary);
    color: white;
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-semibold);
    border-radius: var(--border-radius-full);
  }

  .worker-info {
    flex: 1;
    min-width: 0;
  }

  .worker-name {
    font-size: var(--font-size-base);
    font-weight: var(--font-weight-semibold);
    color: var(--text-primary);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .worker-id {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
    font-family: var(--font-mono);
  }

  .worker-status {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    font-size: var(--font-size-xs);
    color: var(--color-success);
  }

  .worker-status-dot {
    width: 0.5rem;
    height: 0.5rem;
    background-color: var(--color-success);
    border-radius: 50%;
  }

  .worker-card-body {
    padding: var(--spacing-md) var(--spacing-lg);
  }

  .worker-detail {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: var(--spacing-sm) 0;
  }

  .worker-detail-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: var(--font-size-sm);
    color: var(--text-secondary);
  }

  .worker-detail-value {
    font-size: var(--font-size-sm);
    color: var(--text-primary);
  }

  .workers-empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: var(--spacing-2xl);
    color: var(--text-muted);
  }

  .workers-empty-icon {
    width: 3rem;
    height: 3rem;
    margin-bottom: var(--spacing-md);
  }

  .workers-empty-text {
    font-size: var(--font-size-sm);
  }
</style>
